#!/bin/sh
#
# Gradle startup script for POSIX generated by 'gradle init'
# SPDX-License-Identifier: Apache-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by 'gradle init'
#
#   Important for the exec hands-off approach:
#   DEFAULT_JVM_OPTS values must be individually quoted so that the shell
#   splits them correctly (eval is used below for this purpose).
#
##############################################################################

# Attempt to set APP_HOME
app_path=$0
while [ -h "$app_path" ] ; do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
        /*)   app_path=$link ;;
        *)    app_path=$( dirname "$app_path" )/$link ;;
    esac
done
APP_HOME=$( cd "$( dirname "$app_path" )" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Default JVM options — quoted tokens, eval-expanded below
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD=maximum

warn () { echo "$*"; } >&2
die  () { echo; echo "$*"; echo; exit 1; } >&2

cygwin=false; msys=false; darwin=false; nonstop=false
case "$( uname )" in
    CYGWIN* )  cygwin=true  ;;
    Darwin* )  darwin=true  ;;
    MSYS* | MINGW* ) msys=true ;;
    NONSTOP* ) nonstop=true ;;
esac

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command found in PATH."
fi

if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in
        max*)
            MAX_FD=$( ulimit -H -n ) || warn "Could not query maximum file descriptor limit"
            ;;
    esac
    case $MAX_FD in
        '' | soft) ;;
        *) ulimit -n "$MAX_FD" || warn "Could not set maximum file descriptor limit to $MAX_FD" ;;
    esac
fi

# Build the command using eval so that DEFAULT_JVM_OPTS tokens with
# embedded quotes are properly word-split (this is the official Gradle approach)
eval set -- \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    '"-Dorg.gradle.appname=$APP_BASE_NAME"' \
    '-classpath' '"$CLASSPATH"' \
    'org.gradle.wrapper.GradleWrapperMain' \
    '"$@"'

exec "$JAVACMD" "$@"
