package com.systemsgo.hex.snmp.mib

import com.systemsgo.hex.snmp.protocol.Oid

/**
 * A pragmatic reader for standard textual SMIv1/SMIv2 MIB files — resolves
 * every `name ::= { parent child }` style assignment (OBJECT IDENTIFIER,
 * OBJECT-TYPE, NOTIFICATION-TYPE/TRAP-TYPE, MODULE-IDENTITY, OBJECT-GROUP,
 * etc — the clause shape is identical across all of them for our purposes)
 * into a concrete OID, by resolving parent names iteratively against
 * [MibDictionary]'s built-in table and whatever else this same file
 * already resolved.
 *
 * This is deliberately **not** a full SMIv1/SMIv2 compiler: it doesn't
 * parse or validate SYNTAX clauses, doesn't resolve IMPORTS across
 * multiple files (a MIB that references symbols from a separate,
 * not-simultaneously-loaded MIB file will leave those symbols
 * unresolved), doesn't expand macros, and has no notion of textual
 * conventions. For the MIB-browser use case — "load this vendor's MIB so
 * their OIDs show friendly names and I can browse the tree" — resolving
 * the name↔OID assignments is the part that actually matters, and this
 * covers that for the overwhelming majority of real-world MIB files
 * (including every one auto-generated by common vendor toolchains).
 * Load a MIB's IMPORTed dependencies (e.g. its enterprise's own
 * SMI/`-TC` file) in the same call — see [parse]'s `text` parameter,
 * which accepts multiple files concatenated — so cross-file parents
 * resolve too.
 */
object MibParser {

    data class ParseResult(
        val resolved: Map<String, Oid>, // name -> oid
        val unresolvedNames: List<String>,
        val moduleName: String?,
    )

    private val assignmentRegex = Regex(
        """([A-Za-z][A-Za-z0-9-]*)\s+(?:OBJECT-TYPE|OBJECT\s+IDENTIFIER|NOTIFICATION-TYPE|TRAP-TYPE|MODULE-IDENTITY|OBJECT-GROUP|NOTIFICATION-GROUP|MODULE-COMPLIANCE|AGENT-CAPABILITIES)\b[\s\S]*?::=\s*\{\s*([A-Za-z][A-Za-z0-9-]*)\s+(\d+)\s*\}""",
    )
    private val moduleNameRegex = Regex("""^\s*([A-Za-z][A-Za-z0-9-]*)\s+DEFINITIONS\s*(?:::=|\{)""", RegexOption.MULTILINE)

    /**
     * Parses one or more concatenated MIB file bodies. [text] can contain
     * several files back to back (e.g. a vendor enterprise MIB plus the
     * `-TC` textual-conventions file it IMPORTS from) — order doesn't
     * matter, resolution runs to a fixed point across the whole input.
     */
    fun parse(text: String): ParseResult {
        val stripped = stripComments(text)
        val moduleName = moduleNameRegex.find(stripped)?.groupValues?.get(1)

        // name -> (parentName, childArc), for every assignment found, in source order.
        val pending = LinkedHashMap<String, Pair<String, Int>>()
        for (m in assignmentRegex.findAll(stripped)) {
            val name = m.groupValues[1]
            val parent = m.groupValues[2]
            val child = m.groupValues[3].toIntOrNull() ?: continue
            if (name == parent) continue // malformed/self-referential clause — skip rather than loop forever
            pending[name] = parent to child
        }

        val resolved = LinkedHashMap<String, Oid>()
        // Fixed-point resolution: a name resolves once its parent is either already known
        // (built-in dictionary) or was itself resolved in an earlier pass. Bounded by
        // pending.size passes, which is always enough for a DAG with no cycles.
        var progressed = true
        var passes = 0
        while (progressed && passes <= pending.size) {
            progressed = false
            passes++
            for ((name, parentAndChild) in pending) {
                if (resolved.containsKey(name)) continue
                val (parentName, child) = parentAndChild
                val parentOid = resolved[parentName] ?: MibDictionary.oidFor(parentName)
                    ?: WELL_KNOWN_ROOTS[parentName]
                if (parentOid != null) {
                    resolved[name] = parentOid + child
                    progressed = true
                }
            }
        }

        val unresolved = pending.keys.filterNot { resolved.containsKey(it) }
        return ParseResult(resolved, unresolved, moduleName)
    }

    /** Parses [text] and registers every resolved name into [MibDictionary] as a custom (session-scoped) entry; returns the same [ParseResult] for UI feedback (e.g. "42 objects loaded, 3 unresolved"). */
    fun loadInto(text: String): ParseResult {
        val result = parse(text)
        for ((name, oid) in result.resolved) MibDictionary.register(oid.toString(), name, isCustom = true)
        return result
    }

    private fun stripComments(text: String): String {
        // SMI comments run from "--" to end of line (or to the next "--", but end-of-line is the
        // overwhelmingly common form in real files, so that's all this handles).
        return text.lineSequence().joinToString("\n") { line ->
            val idx = line.indexOf("--")
            if (idx >= 0) line.substring(0, idx) else line
        }
    }

    /** Arcs no MIB file ever defines itself (they're baked into ASN.1 / the SMI itself) but that real files still reference as a parent name — the top of every OID tree. */
    private val WELL_KNOWN_ROOTS: Map<String, Oid> = mapOf(
        "iso" to Oid("1"),
        "org" to Oid("1.3"),
        "dod" to Oid("1.3.6"),
        "internet" to Oid("1.3.6.1"),
        "directory" to Oid("1.3.6.1.1"),
        "mgmt" to Oid("1.3.6.1.2"),
        "mib-2" to Oid("1.3.6.1.2.1"),
        "experimental" to Oid("1.3.6.1.3"),
        "private" to Oid("1.3.6.1.4"),
        "enterprises" to Oid("1.3.6.1.4.1"),
        "security" to Oid("1.3.6.1.5"),
        "snmpV2" to Oid("1.3.6.1.6"),
        "snmpModules" to Oid("1.3.6.1.6.3"),
        "snmpMIB" to Oid("1.3.6.1.6.3.1"),
    )
}
